### ISSUE TITLE
Can't add filters

### ISSUE THREAD

**Issue by trudslev** [vanossj/deluge-seedtime#5]
deluged 1.3.14
Windows client 1.3.14

I cannot add filters. Nothing happens when I press the Add button.

**Comment by vanossj** [comment]
I tried deluge 1.3.14 on windows 10 and it is working for me.

What version of seedtime did you use? did you build from master?

Does the webui work?

Could you post a [log](http://dev.deluge-torrent.org/wiki/Troubleshooting#EnableDelugeLogging) of the issue?

**Comment by trudslev** [comment]
Yes, built fron master. I didn't try the web-ui.

Nothing came in the log, but deluge-debug.exe threw this exception:

Unhandled error in Deferred:


Traceback (most recent call last):
  File "twisted/protocols/policies.py", line 120, in dataReceived

  File "deluge\ui\client.py", line 179, in dataReceived

  File "twisted/internet/defer.py", line 393, in callback

  File "twisted/internet/defer.py", line 501, in _startRunCallbacks

--- <exception caught here> ---
  File "twisted/internet/defer.py", line 587, in _runCallbacks

  File "build/bdist.linux-x86_64/egg/seedtime/gtkui.py", line 176, in cb_get_config

exceptions.KeyError: 'delay_time'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/seedtime/gtkui.py", line 196, in btnAddCallback
AttributeError: 'GtkUI' object has no attribute 'liststore'

It looks like it is have a problem with something in my config.

**Comment by vanossj** [comment]
if you are upgrading from an older version of seedtime the config file might be incompatable. Try deleting seedtime.conf file and restarting deluge

**Comment by trudslev** [comment]
It wasn't the config, but some (bad) eggs left behind. The older versions of SeedTime were installed both in the python dist directory, but also deluges plugin directory. I removed the old versions and it is working :)
